spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    view:
      suffix: .html
      prefix: /
  web:
    resources:
      static-locations: file:/root/typora_img/
server:
  port: 8080
filePath: H://typora_img